#!/bin/bash
# Quick reference for common build commands

set -e

echo "=== NEXUS TERMINAL BUILD REFERENCE ==="
echo ""
echo "SETUP (one-time):"
echo "  export ANDROID_HOME=/path/to/Android/Sdk"
echo "  chmod +x gradlew"
echo ""
echo "BUILD & TEST:"
echo "  ./gradlew assembleDebug          # Build debug APK"
echo "  ./gradlew assembleRelease        # Build release APK (needs signing config)"
echo "  ./gradlew test                   # Run unit tests"
echo "  ./gradlew lint                   # Run lint checks"
echo "  ./gradlew clean                  # Clean build artifacts"
echo ""
echo "INSTALL & RUN:"
echo "  adb install -r app/build/outputs/apk/debug/app-debug.apk"
echo "  adb shell am start -n com.nexus.terminal/.MainActivity"
echo ""
echo "RELEASE BUILD (with signing):"
echo "  export KEYSTORE_PATH=$(pwd)/release.jks"
echo "  export KEYSTORE_PASSWORD=your_password"
echo "  export KEY_ALIAS=nexus"
echo "  export KEY_PASSWORD=your_key_password"
echo "  ./gradlew assembleRelease"
echo ""
echo "REPORTS:"
echo "  # After build:"
echo "  open app/build/reports/tests/test/index.html        # Test results"
echo "  open app/build/reports/lint-results.html            # Lint results"
echo ""
