package com.nexus.terminal.data

import android.content.Context
import com.nexus.terminal.util.NxPaths
import com.nexus.terminal.util.Tsv
import java.io.File

/** Process-wide command history, honoring settings. */
object CommandHistory {
    private var store: HistoryStore? = null

    fun init(ctx: Context) {
        store = HistoryStore(File(NxPaths.data(ctx), "history.tsv"), AppSettings.historySize)
    }

    fun add(cmd: String) { if (AppSettings.recordHistory) store?.add(cmd) }
    fun all(): List<HistoryStore.Entry> = store?.all().orEmpty()
    fun search(q: String) = store?.search(q).orEmpty()
    fun remove(e: HistoryStore.Entry) { store?.remove(e) }
    fun clear() { store?.clear() }
    fun setMax(n: Int) { AppSettings.historySize = n; store?.setMax(n) }
}

enum class BookmarkType { COMMAND, DIRECTORY, FILE, SESSION }
data class Bookmark(val type: BookmarkType, val label: String, val value: String)

object BookmarkStore {
    fun all(): List<Bookmark> = Tsv.decodeAll(AppSettings.bookmarks).mapNotNull {
        if (it.size < 3) null else runCatching { Bookmark(BookmarkType.valueOf(it[0]), it[1], it[2]) }.getOrNull()
    }

    private fun save(list: List<Bookmark>) {
        AppSettings.bookmarks = Tsv.encodeAll(list.map { listOf(it.type.name, it.label, it.value) })
    }

    fun add(b: Bookmark) { val l = all(); if (l.none { it.type == b.type && it.value == b.value }) save(l + b) }
    fun remove(b: Bookmark) { save(all().filterNot { it == b }) }
    fun has(type: BookmarkType, value: String) = all().any { it.type == type && it.value == value }
}

data class AliasDef(val name: String, val command: String)

object AliasStore {
    private val nameRe = Regex("[A-Za-z0-9_.-]+")
    fun isValidName(n: String) = nameRe.matches(n)

    fun all(): List<AliasDef> = Tsv.decodeAll(AppSettings.aliases).mapNotNull {
        if (it.size < 2) null else AliasDef(it[0], it[1])
    }

    fun render(list: List<AliasDef>): String = buildString {
        appendLine("# Generated by Nexus Terminal (Settings > Shell > Aliases). Safe to delete.")
        list.forEach { appendLine("alias ${it.name}='${it.command.replace("'", "'\\''")}'") }
    }

    fun save(ctx: Context, list: List<AliasDef>) {
        AppSettings.aliases = Tsv.encodeAll(list.map { listOf(it.name, it.command) })
        File(NxPaths.home(ctx), ".nexus_aliases").writeText(render(list))
    }
}

data class EnvVar(val name: String, val value: String)

object EnvStore {
    private val nameRe = Regex("[A-Za-z_][A-Za-z0-9_]*")
    fun isValidName(n: String) = nameRe.matches(n)

    fun all(): List<EnvVar> = Tsv.decodeAll(AppSettings.envVars).mapNotNull {
        if (it.size < 2) null else EnvVar(it[0], it[1])
    }

    fun save(list: List<EnvVar>) {
        AppSettings.envVars = Tsv.encodeAll(list.map { listOf(it.name, it.value) })
    }
}

data class ShortcutDef(val label: String, val payload: String)

object ShortcutStore {
    fun custom(): List<ShortcutDef> = Tsv.decodeAll(AppSettings.customShortcuts).mapNotNull {
        if (it.size < 2) null else ShortcutDef(it[0], it[1])
    }
    fun saveCustom(list: List<ShortcutDef>) {
        AppSettings.customShortcuts = Tsv.encodeAll(list.map { listOf(it.label, it.payload) })
    }

    /** Built-in Ctrl combinations (control bytes). */
    val builtin = listOf(
        ShortcutDef("Ctrl+C", "\u0003"), ShortcutDef("Ctrl+D", "\u0004"), ShortcutDef("Ctrl+L", "\u000c"),
        ShortcutDef("Ctrl+R", "\u0012"), ShortcutDef("Ctrl+Z", "\u001a"), ShortcutDef("Ctrl+A", "\u0001"),
        ShortcutDef("Ctrl+E", "\u0005"), ShortcutDef("Ctrl+K", "\u000b"), ShortcutDef("Ctrl+U", "\u0015"),
        ShortcutDef("Ctrl+W", "\u0017")
    )
}
